<template>
<div>
  <div id='container' style="width: 100%;height: 100%"></div>
</div>
</template>

<script>

//
// Generated by the Exaile Playlist Analyzer plugin.
// (C) 2014 Dustin Spicuzza <dustin@virtualroadside.com>
//
// This work is licensed under the Creative Commons Attribution 4.0
// International License. To view a copy of this license, visit
// http://creativecommons.org/licenses/by/4.0/.
//
// Inspired by http://www.findtheconversation.com/concept-map/
// Loosely based on http://bl.ocks.org/mbostock/4063550
//

import * as d3 from 'd3';
export default {
  name: "ConceptMap",
  data(){
    return{
      typeData:[
        {type:1,
          AAs:["Arg", "Asp", "Cys", "Gln", "Glu", "Ile", "Phe", "Pro"],
          visualParams:{
            direction:"right",
            rectHeight:80,
            rectWidth:130,
            color:"#fce38a"
          }
        },
        {type:2,
          AAs:["Asn", "Gly", "His", "Lys", "Met", "Thr", "Trp", "Tyr", "Val"],
          visualParams:{
            direction:"left",
            rectHeight:80,
            rectWidth:150,
            color:"#95e1d3"
          }},
        {type:3,AAs:["Ala", "Leu", "Ser"],
          visualParams:{
            direction:"right",
            rectHeight:60,
            rectWidth:100,
            color: "#f38181"
          }}
      ],
      mapData : [
        ["-1", []],
        [1, ["type1", "type2"]],
        [2, ["type1", "type2", "type3"]],
        [3, ["type1", "type2", "type3"]],
        [4, ["type2", "type3"]],
        [5, []],
        [6, []],
        [7, []],
        [8, ["type3"]],
        [9, []],
        [10, []],
        [11, ["type1", "type3"]],
        [12, ["type1"]],
        [13, ["type1"]],
        [14, ["type3"]],
        [15, ["type1"]],
        [16, []],
        [17, []],
        ["17a", []],
        [18, []],
        [19, []],
        [20, []],
        ["20a", []],
        ["20b", []],
        [21, []],
        [22, ["type1"]],
        [23, ["type1"]],
        [24, ["type1", "type3"]],
        [25, []],
        [26, []],
        [27, ["type1"]],
        [28, ["type1"]],
        [29, ["type1"]],
        [30, []],
        [31, []],
        [32, ["type1", "type2"]],
        [33, ["type1", "type2"]],
        [34, ["type1", "type2"]],
        [35, ["type1", "type2"]],
        [36, ["type1", "type2"]],
        [37, ["type1", "type2"]],
        [38, ["type1", "type2"]],
        [39, []],
        [40, []],
        [41, ["type1"]],
        [42, ["type1"]],
        [43, ["type1"]],
        [44, []],
        [45, ["type1"]],
        [46, ["type1"]],
        [47, ["type1"]],
        [48, ["type1"]],
        [49, []],
        [50, []],
        [51, ["type3"]],
        [52, []],
        [53, []],
        [54, []],
        [55, []],
        [56, []],
        [57, []],
        [58, []],
        [59, ["type1"]],
        [60, ["type1"]],
        [61, []],
        [62, []],
        [63, []],
        [64, []],
        [65, []],
        [66, []],
        [67, []],
        [68, []],
        [69, ["type2", "type3"]],
        [70, ["type1", "type2", "type3"]],
        [71, ["type1", "type2", "type3"]],
        [72, ["type1", "type2", "type3"]],
        [73, ["type1", "type2", "type3"]]
      ],
    }
  },
  methods:{
    drawConceptMap(data){
      // tRNA位置的坐标
      let tRNAx=[
        -2,
        -2,
        -2,
        -2,
        -2,
        -2,
        -2,
        -2,
        -18,
        -39,
        -65,
        -92,
        -119,
        -145,
        -163,
        -184,
        -208,
        -232,
        -249,
        -255,
        -249,
        -233,
        -209,
        -185,
        -163,
        -145,
        -119,
        -92,
        -65,
        -43,
        -29,
        -29,
        -29,
        -29,
        -29,
        -40,
        -45,
        -31,
        -6,
        17,
        32,
        26,
        17,
        17,
        17,
        17,
        17,
        16,
        43,
        71,
        83,
        68,
        63,
        90,
        117,
        144,
        172,
        196,
        220,
        242,
        253,
        242,
        219,
        196,
        172,
        144,
        117,
        90,
        63,
        44,
        44,
        44,
        44,
        44,
        44,
        44,
        44
      ]
      let tRNAy=[
        -255,
        -228,
        -201,
        -174,
        -147,
        -121,
        -93,
        -67,
        -44,
        -25,
        -12,
        -12,
        -12,
        -12,
        -29,
        -42,
        -44,
        -35,
        -17,
        8,
        35,
        53,
        62,
        60,
        47,
        33,
        33,
        33,
        33,
        49,
        70,
        97,
        123,
        151,
        176,
        198,
        222,
        244,
        256,
        246,
        223,
        199,
        176,
        151,
        123,
        97,
        70,
        45,
        54,
        64,
        41,
        21,
        -5,
        -5,
        -5,
        -5,
        -5,
        6,
        11,
        -4,
        -29,
        -52,
        -66,
        -60,
        -51,
        -51,
        -51,
        -51,
        -51,
        -67,
        -93,
        -121,
        -147,
        -174,
        -201,
        -228,
        -255
      ]
      let diameter = 960;
      let link_width = "1px";


      let outer = new Map();
      let inner = [];
      let links = [];

      let outerId = [0];

      data.forEach(function(d){

        if (d == null)
          return;

        let i = { id: 'i' + inner.length, name: d[0], related_links: [] };
        i.related_nodes = [i.id];
        inner.push(i);

        if (!Array.isArray(d[1]))
          d[1] = [d[1]];

        d[1].forEach(function(d1){

          let o = outer.get(d1);

          if (o == null)
          {
            o = { name: d1,	id: 'o' + outerId[0], related_links: [] };
            o.related_nodes = [o.id];
            outerId[0] = outerId[0] + 1;

            outer.set(d1, o);
          }

          // create the links
          let l = { id: 'mod-l-' + i.id + '-' + o.id, inner: i, outer: o }
          links.push(l);

          // and the relationships
          i.related_nodes.push(o.id);
          i.related_links.push(l.id);
          o.related_nodes.push(i.id);
          o.related_links.push(l.id);
        });
      });

      data = {
        inner: inner,
        outer: outer.values(),
        links: links
      }

      // 排列outer
      outer = Array.from(data.outer);
      data.outer = Array(outer.length);


      let i1 = 0;
      let i2 = outer.length - 1;

      for (let i = 0; i < data.outer.length; ++i)
      {
        if (i % 2 == 1)
          data.outer[i2--] = outer[i];
        else
          data.outer[i1++] = outer[i];
      }




      let mid = (data.outer.length/2.0)
      let outer_x = d3.scaleLinear()
          .domain([0, mid, mid, data.outer.length])
          .range([15, 170, 190 ,355]);

      //设置位置
      data.outer = data.outer.map(function(d, i) {
        d.x = outer_x(i);
        d.y = diameter /3;
        return d;
      });

      data.inner = data.inner.map(function(d, i) {
        d.x = tRNAx[i]
        d.y = tRNAy[i]
        return d;
      });

      function projectX(x)
      {
        return ((x - 90) / 180 * Math.PI) - (Math.PI/2);
      }
      var diagonal = d3.linkHorizontal()
          .x(function(d) { return d.x; })
          .y(function(d) { return d.y; });

      var svg = d3.select("#container").append("svg")
          .attr("width","700px")
          .attr("height", "700px")
          .attr("viewBox", "0 0 960 960")
          .append("g")
          .attr("transform", "translate(" + diameter / 2 + "," + diameter / 2 + ")");


      var link = svg.append('g').attr('class', 'links_mod').selectAll(".link_mod")
          .data(data.links)
          .enter().append('path')
          .attr('class', 'link')
          .attr('id', function(d) { return d.id })
          .attr("d", function(d) {
            return diagonal({ source: { x: -d.outer.y * Math.sin(projectX(d.outer.x)), y: d.outer.y * Math.cos(projectX(d.outer.x)) }, target: { x: d.inner.x, y: d.inner.y} });
          })
          .attr('stroke', '#dddddd' )
          .attr('fill-opacity',0)
          .attr('stroke-width', link_width);

      data.outer.forEach((element, index) => {
        element.typeData = this.typeData[index];
      });

      var onode = svg.append('g').selectAll(".outer_node")
          .data(data.outer)
          .enter().append("g")
          .attr("class", "outer_node")
          .attr("transform", function(d) { return "translate(" + d.y * Math.cos((d.x - 90) * Math.PI / 180) + " " + d.y * Math.sin((d.x - 90) * Math.PI / 180) + ")"; })
          .on("mouseover", mouseover)
          .on("mouseout", mouseout);



      onode.append("circle")
          .attr('r', 20)
          .attr('visibility', 'hidden');

      var textGroup = onode.append("g")
          .attr("class", "text-group");

      textGroup.append("rect")
          .attr('id', function(d) { return d.id+ '-rect'; })
          .attr("stroke", "steelblue")
          .attr("stroke-width", "1.5px")
          .attr('x',function(d) { return d.typeData.visualParams.direction === "right" ? 0 :-d.typeData.visualParams.rectWidth; })
          .attr("width", function(d) { return d.typeData.visualParams.rectWidth })
          .attr("height", function(d){ return d.typeData.visualParams.rectHeight })
          .attr("rx", 5)
          .attr("ry", 5)
          .attr("fill", function(d){ return d.typeData.visualParams.color });

      textGroup.append("text")
          .attr("x", function(d) { return d.typeData.visualParams.direction === "right" ? 10 :-d.typeData.visualParams.rectWidth+10; })
          .attr("y", 20)
          .text(function(d) { return 'Type '+d.typeData.type; })
          .style("font-size", "14px")
          .style("font-weight", "bold");

      textGroup.append("foreignObject")
          .attr("x", function(d) { return d.typeData.visualParams.direction === "right" ? 10 :-d.typeData.visualParams.rectWidth+10; })
          .attr("y", 30)
          .attr("width", function(d) { return d.typeData.visualParams.rectWidth })  // 设置宽度
          .attr("height", function(d){ return d.typeData.visualParams.rectHeight-30})  // 设置高度
          .append("xhtml:div")
          .style("font-size", "12px")
          .style("width", "100%")
          .style("height", "100%")
          .style("display", "flex")       // 使用 flex 布局
          .style("flex-wrap", "wrap")     // 自动换行
          .html(function(d) {
            // 使用数组中的每个元素创建换行文本
            return d.typeData.AAs.map(function(item) {
              return '<div style="margin-right: 10px;">' + item + '</div>';  // 每个元素之间加上右边距
            }).join('');
          });

      onode.append("circle")
          .attr('id', function(d) { return d.id; })
          .attr("r", 4.5)
          .attr("fill", "#fff")
          .attr("stroke", "steelblue")
          .attr("stroke-width", "1.5px");

      // inner nodes

      var inode = svg.append('g').selectAll(".inner_node")
          .data(data.inner)
          .enter().append("g")
          .attr("class", "inner_node")
          .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"})
          .on("mouseover", mouseover)
          .on("mouseout", mouseout);

      inode.append('circle')
          .attr('r',12)
          .attr('stroke', "black")
          .attr('id', function(d) { return d.id; })
          .attr('fill', '#dddddd');

      inode.append("text")
          .attr('id', function(d) { return d.id + '-txt'; })
          .attr('text-anchor', 'middle')
          .attr("transform", "translate(0,5)")
          .attr('fill', "black")
          .text(function(d) { return d.name; });

// need to specify x/y/etc

      d3.select(self.frameElement).style("height", diameter - 150 + "px");

      function mouseover(event,d)
      {
        let i;
// bring to front
        d3.selectAll('.links .link').sort(function(a){ return d.related_links.indexOf(a.id); });
        for (i = 0; i < d.related_nodes.length; i++)
        {

          d3.select('#' + d.related_nodes[i]).classed('highlight', true);
          d3.select('#' + d.related_nodes[i]).style('fill', d.typeData?d.typeData.visualParams.color:"#dddddd");
        }

        for (i = 0; i < d.related_links.length; i++)
          d3.select('#' + d.related_links[i]).attr('stroke', d.typeData?d.typeData.visualParams.color:"#dddddd").attr('stroke-width', '5px');

      }


      function mouseout(event,d)
      {
        for (i = 0; i < d.related_nodes.length; i++)
        {
          d3.select('#' + d.related_nodes[i]).classed('highlight', false);
          d3.select('#' + d.related_nodes[i]).style('fill',"#dddddd");
        }

        for (var i = 0; i < d.related_links.length; i++)
          d3.select('#' + d.related_links[i]).attr('stroke',"#dddddd").attr('stroke-width', link_width);

      }

    }
  },
  mounted() {
    this.drawConceptMap(this.mapData)
  },
}
</script>

