import { ref, type Ref } from 'vue';
import { CHAT_GREETING } from './chatGreeting';
import { initializeChatIdentity } from './chatIdentity';
import {
  sanitizeAssistantResponse,
  sanitizeAssistantSources,
  sanitizeAssistantText
} from './chatContentSafety';

type ChatMessage = {
  id: number;
  text: string;
  sender: string;
  image?: string | null;
  sources?: Record<string, unknown>[];
};

type ChatToolTrace = {
  id: number;
  tool: string;
  summary: string;
};

type ChatJudgeTrace = {
  id: number;
  verdict: string;
  summary: string;
  coverageScore?: number | null;
  missingAspects?: string[];
  nextTools?: string[];
};

type ChatDraftPreview = {
  label: string;
  content: string;
};

type ChatHistoryMessage = {
  role: 'user' | 'assistant';
  content: string;
};

type ChatSession = {
  apiKey: string;
  isChatOpen: Ref<boolean>;
  messages: Ref<ChatMessage[]>;
  newMessage: Ref<string>;
  newImage: Ref<File | null>;
  imagePreview: Ref<string>;
  isStreaming: Ref<boolean>;
  applicationId: string;
  chatId: string;
  initialized: boolean;
  initializing: Promise<void> | null;
  streamAbortController: AbortController | null;
  progressStatus: Ref<string>;
  progressDetail: Ref<string>;
  progressToolTrace: Ref<ChatToolTrace[]>;
  progressJudgeTrace: Ref<ChatJudgeTrace[]>;
  progressDraftPreview: Ref<ChatDraftPreview | null>;
};

type SendOptions = {
  skipUserPush?: boolean;
  overrideText?: string;
  model?: string;
  history?: ChatHistoryMessage[];
  deepReview?: boolean;
  thinkingEnabled?: boolean;
};

const sessions = new Map<string, ChatSession>();
const apiBaseURL = import.meta.env.VITE_CHAT_API_BASE || '/chat/api';

const debugChatLog = (...args: unknown[]) => {
  // @ts-ignore
  if (import.meta.env?.VITE_DEBUG_CHAT_LOG === '1') {
    console.log(...args);
  }
};

const logAuth = (_session: ChatSession, where: string, url: string, method: string) => {
  debugChatLog(`[useChat] ${method} ${url} (${where})`);
};

const authHeaders = (_session: ChatSession) => ({ accept: 'application/json' });

const composeBotMessageText = (main: string, evidence: string) => {
  const mainText = String(main || '').trim();
  const evidenceText = String(evidence || '').trim();
  return evidenceText ? `${mainText}\n\nSearch results:\n${evidenceText}`.trim() : mainText;
};

const GENERIC_STREAM_ERROR = 'Sorry, I could not process your request. Please try again.';

const PROVIDER_NOTICE = {
  xiaomi_relay: 'Model notice: official MiMo unavailable; generated through configured MiMo-compatible relay.',
  deepseek: 'Model notice: MiMo was unavailable, so this answer was generated by the configured DeepSeek fallback.'
} as const;

/**
 * Convert provider routing metadata into one of our own fixed notices. Never
 * render server-provided labels, endpoints, or failure reasons: the execution
 * trace may contain operational details and must be treated as untrusted data.
 */
const providerExecutionNotice = (execution: unknown, legacyFallback: unknown) => {
  if (execution && typeof execution === 'object' && !Array.isArray(execution)) {
    const metadata = execution as Record<string, unknown>;
    const logicalProvider = metadata.logical_provider;
    const finalEndpoint = metadata.final_endpoint;
    if (logicalProvider === 'xiaomi') {
      if (finalEndpoint === 'xiaomi_relay') return PROVIDER_NOTICE.xiaomi_relay;
      if (finalEndpoint === 'deepseek') return PROVIDER_NOTICE.deepseek;
      return '';
    }
    // An explicitly selected DeepSeek model is not a MiMo fallback. Treat a
    // recognized new-schema provider as authoritative instead of consulting
    // stale legacy metadata that could produce a false notice.
    if (logicalProvider === 'deepseek') return '';
  }

  // Backward compatibility for evidence events emitted before
  // provider_execution was introduced. Only the exact historical enum pair
  // is accepted; arbitrary backend text is intentionally ignored.
  if (legacyFallback && typeof legacyFallback === 'object' && !Array.isArray(legacyFallback)) {
    const fallback = legacyFallback as Record<string, unknown>;
    if (fallback.from_provider === 'xiaomi' && fallback.to_provider === 'deepseek') {
      return PROVIDER_NOTICE.deepseek;
    }
  }
  return '';
};

const getSession = (key: string, apiKey: string): ChatSession => {
  const existing = sessions.get(key);
  if (existing) return existing;
  const session: ChatSession = {
    apiKey,
    isChatOpen: ref(false),
    messages: ref<ChatMessage[]>([{ id: 1, text: CHAT_GREETING, sender: 'bot' }]),
    newMessage: ref(''),
    newImage: ref<File | null>(null),
    imagePreview: ref(''),
    isStreaming: ref(false),
    applicationId: '',
    chatId: '',
    initialized: false,
    initializing: null,
    streamAbortController: null,
    progressStatus: ref(''),
    progressDetail: ref(''),
    progressToolTrace: ref<ChatToolTrace[]>([]),
    progressJudgeTrace: ref<ChatJudgeTrace[]>([]),
    progressDraftPreview: ref<ChatDraftPreview | null>(null)
  };
  sessions.set(key, session);
  return session;
};

const fetchApplicationProfile = async (session: ChatSession, signal?: AbortSignal) => {
  try {
    const url = `${apiBaseURL}/application/profile`;
    logAuth(session, 'profile', url, 'GET');

    const response = await fetch(url, {
      method: 'GET',
      headers: authHeaders(session),
      credentials: 'same-origin',
      signal
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const data = await response.json();
    session.applicationId = data?.data?.id || '';
    debugChatLog('[useChat] applicationId:', session.applicationId);
  } catch (e) {
    console.error('Error fetching application profile:', e);
  }
};

const openChatSession = async (session: ChatSession, signal?: AbortSignal) => {
  try {
    const url = `${apiBaseURL}/open?application_id=${encodeURIComponent(session.applicationId)}&ts=${Date.now()}`;
    logAuth(session, 'open', url, 'GET');

    let response = await fetch(url, {
      method: 'GET',
      headers: authHeaders(session),
      credentials: 'same-origin',
      cache: 'no-store',
      signal
    });
    if (!response.ok && (response.status === 400 || response.status === 404)) {
      const fallbackUrl = `${apiBaseURL}/open?ts=${Date.now()}`;
      logAuth(session, 'open(fallback)', fallbackUrl, 'GET');
      response = await fetch(fallbackUrl, {
        method: 'GET',
        headers: authHeaders(session),
        credentials: 'same-origin',
        cache: 'no-store',
        signal
      });
    }
    if (!response.ok) throw new Error(`HTTP ${response.status}`);

    const data = await response.json();
    session.chatId = data?.data || '';
    debugChatLog('[useChat] chatId:', session.chatId);
  } catch (e) {
    console.error('Error opening chat session:', e);
  }
};

const initializeChatSession = async (session: ChatSession, signal?: AbortSignal) => {
  if (session.chatId) {
    session.initialized = true;
    return;
  }
  if (session.initializing) {
    return session.initializing;
  }
  debugChatLog('[useChat] apiBaseURL:', apiBaseURL);
  session.initializing = (async () => {
    try {
      // Ensure the anonymous visitor cookie is established before profile/open.
      // All callers share the same initialization promise, preventing races that
      // could otherwise bind a chat id to a different freshly-issued identity.
      await initializeChatIdentity();
      if (!session.applicationId) {
        await fetchApplicationProfile(session, signal);
      }
      if (!session.chatId) {
        await openChatSession(session, signal);
      }
      session.initialized = Boolean(session.chatId);
    } finally {
      session.initializing = null;
    }
  })();
  return session.initializing;
};

type UseChatOptions = {
  key?: string;
};

export const warmChatSession = async (apiKey: string, key: string) => {
  const session = getSession(key, apiKey);
  session.apiKey = apiKey;
  await initializeChatSession(session);
};

export function useChat(apiKey: string, options: UseChatOptions = {}) {
  const key = options.key || 'default';
  const session = getSession(key, apiKey);
  session.apiKey = apiKey;

  const toggleChat = () => { session.isChatOpen.value = !session.isChatOpen.value; };
  const stopMessage = () => {
    session.streamAbortController?.abort();
  };

  const ensureReady = async (signal?: AbortSignal) => {
    await initializeChatSession(session, signal);
  };

  // 3) 发送消息（POST /chat/api/chat_message/{chat_id}）
  const sendMessage = async (options: SendOptions = {}) => {
    if (session.isStreaming.value) return { aborted: false };
    const overrideText = options.overrideText ?? '';
    const pendingText = overrideText ? overrideText : session.newMessage.value;
    if (!pendingText.trim() && !session.newImage.value) return;

    const textContent = pendingText.trim();
    const imageBase64 = session.newImage.value ? await toBase64(session.newImage.value) : null;
    let userMessageId: number | null = null;

    if (!options.skipUserPush) {
      userMessageId = Date.now();
      session.messages.value.push({
        id: userMessageId,
        sender: 'user',
        text: textContent,
        image: imageBase64
      });
    }
    session.newMessage.value = '';
    session.newImage.value = null;
    session.imagePreview.value = '';
    session.progressStatus.value = 'Preparing request';
    session.progressDetail.value = 'Opening the chat session and getting the response pipeline ready.';
    session.progressToolTrace.value = [];
    session.progressJudgeTrace.value = [];
    session.progressDraftPreview.value = null;

    const controller = new AbortController();
    session.streamAbortController = controller;
    session.isStreaming.value = true;

    let botMessageId: number | null = null;
    let complete = '';
    let evidence = '';

    try {
      await ensureReady(controller.signal);
      if (!session.chatId) {
        console.error('Chat ID is not available. Unable to send message.');
        session.messages.value.push({
          id: Date.now(),
          text: 'Sorry, I could not process your request.',
          sender: 'bot'
        });
        return { aborted: false };
      }

      const payload: Record<string, any> = {
        message: textContent,
        re_chat: false,
        stream: true
      };
      if (options.model) payload.model = options.model;
      if (Array.isArray(options.history) && options.history.length) {
        payload.history = options.history;
      }
      if (typeof options.deepReview === 'boolean') {
        payload.deep_review = options.deepReview;
      }
      if (typeof options.thinkingEnabled === 'boolean') {
        payload.thinking_enabled = options.thinkingEnabled;
      }

      const postMessage = async () => {
        const url = `${apiBaseURL}/chat_message/${encodeURIComponent(session.chatId)}`;
        logAuth(session, 'sendMessage', url, 'POST');
        return fetch(url, {
          method: 'POST',
          headers: { ...authHeaders(session), 'Content-Type': 'application/json' },
          credentials: 'same-origin',
          body: JSON.stringify(payload),
          signal: controller.signal
        });
      };

      let response = await postMessage();
      if (response.status === 404) {
        // A deploy, cookie expiry, or explicit cookie reset can invalidate an
        // old signed chat id. Re-open exactly once before surfacing an error.
        session.chatId = '';
        session.initialized = false;
        await initializeChatSession(session, controller.signal);
        if (!session.chatId) throw new Error('Chat session could not be reopened.');
        response = await postMessage();
      }
      if (!response.ok) throw new Error(`HTTP ${response.status}`);

      if (!response.body) throw new Error('ReadableStream not supported.');

      const reader = response.body.getReader();
      const decoder = new TextDecoder('utf-8');
      botMessageId = Date.now();

      let buffer = '';
      let streamFailed = false;

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          if (!line.startsWith('data: ')) continue;
          const jsonStr = line.slice(6);
          if (jsonStr === '[DONE]') continue;
          try {
            const parsed = JSON.parse(jsonStr);
            const eventType = String(parsed?.type || 'content');
            if (eventType === 'error') {
              // Error payloads can contain provider exceptions, SQLAlchemy
              // statements, or other internal details. Never append them to an
              // answer; end this stream with one fixed user-facing message.
              complete = GENERIC_STREAM_ERROR;
              evidence = '';
              session.progressStatus.value = 'Unable to complete the request';
              session.progressDetail.value = 'Please try again in a moment.';
              session.progressDraftPreview.value = null;
              const effectiveId = botMessageId ?? Date.now();
              if (botMessageId === null) botMessageId = effectiveId;
              let message = session.messages.value.find(v => v.id === botMessageId);
              if (!message) {
                message = { id: effectiveId, text: '', sender: 'bot' };
                session.messages.value.push(message);
              }
              message.text = GENERIC_STREAM_ERROR;
              delete message.sources;
              streamFailed = true;
              await reader.cancel();
              break;
            }
            if (eventType === 'status') {
              session.progressStatus.value = sanitizeAssistantText(
                parsed?.status,
                'Working on your answer'
              ).trim() || 'Working on your answer';
              session.progressDetail.value = sanitizeAssistantText(parsed?.detail).trim();
              continue;
            }
            if (eventType === 'tool') {
              const tool = sanitizeAssistantText(parsed?.tool).trim();
              const summary = sanitizeAssistantText(parsed?.summary).trim();
              if (tool || summary) {
                session.progressToolTrace.value = [
                  ...session.progressToolTrace.value,
                  {
                    id: Date.now() + session.progressToolTrace.value.length,
                    tool: tool || 'ENSURE search',
                    summary
                  }
                ];
              }
              continue;
            }
            if (eventType === 'judge') {
              const summary = sanitizeAssistantText(parsed?.summary).trim();
              const verdict = sanitizeAssistantText(parsed?.verdict).trim();
              const coverageRaw = parsed?.coverage_score;
              const coverageScore = typeof coverageRaw === 'number' ? coverageRaw : Number.isFinite(Number(coverageRaw)) ? Number(coverageRaw) : null;
              const missingAspects = Array.isArray(parsed?.missing_aspects)
                ? parsed.missing_aspects.map((item: unknown) => sanitizeAssistantText(item).trim()).filter(Boolean)
                : [];
              const nextTools = Array.isArray(parsed?.next_tools)
                ? parsed.next_tools.map((item: unknown) => sanitizeAssistantText(item).trim()).filter(Boolean)
                : [];
              if (verdict || summary || missingAspects.length || nextTools.length || coverageScore !== null) {
                session.progressJudgeTrace.value = [
                  ...session.progressJudgeTrace.value,
                  {
                    id: Date.now() + session.progressJudgeTrace.value.length,
                    verdict,
                    summary,
                    coverageScore,
                    missingAspects,
                    nextTools
                  }
                ];
              }
              if (summary) {
                session.progressDetail.value = summary;
              }
              continue;
            }
            if (eventType === 'draft_preview') {
              const label = sanitizeAssistantText(parsed?.label, 'Draft answer preview').trim() || 'Draft answer preview';
              const content = sanitizeAssistantText(parsed?.content).trim();
              session.progressDraftPreview.value = content ? { label, content } : null;
              continue;
            }
            if (eventType === 'evidence') {
              const evidencePayload = parsed?.content;
              const rawEvidence = typeof evidencePayload === 'string'
                ? evidencePayload.trim()
                : String(evidencePayload?.text || evidencePayload?.content || '').trim();
              const fallbackNotice = providerExecutionNotice(
                parsed?.provider_execution,
                parsed?.provider_fallback
              );
              const candidateEvidence = [fallbackNotice, rawEvidence].filter(Boolean).join('\n\n');
              const rawSources = Array.isArray(parsed?.sources)
                ? parsed.sources
                : (Array.isArray(evidencePayload?.sources) ? evidencePayload.sources : []);
              const safeResponse = sanitizeAssistantResponse(complete, candidateEvidence);
              evidence = safeResponse.evidence;
              const safeSources = sanitizeAssistantSources(rawSources);
              const effectiveId = botMessageId ?? Date.now();
              if (botMessageId === null) botMessageId = effectiveId;
              const hasBotMessage = session.messages.value.some(v => v.id === botMessageId);
              if (!hasBotMessage) {
                session.messages.value.push({ id: effectiveId, text: '', sender: 'bot' });
              }
              const m = session.messages.value.find(v => v.id === botMessageId);
              if (m) {
                m.text = composeBotMessageText(safeResponse.main, safeResponse.evidence);
                if (safeSources.length) m.sources = safeSources;
                else delete m.sources;
              }
              continue;
            }
            // Only answer/clarification events may contribute visible answer
            // text. Unknown event types are metadata and are ignored.
            if (eventType !== 'content' && eventType !== 'clarification') continue;
            const content = parsed?.content ?? '';
            if (content) {
              complete += content;
              const effectiveId = botMessageId ?? Date.now();
              if (botMessageId === null) botMessageId = effectiveId;
              const hasBotMessage = session.messages.value.some(v => v.id === botMessageId);
              if (!hasBotMessage) {
                session.messages.value.push({ id: effectiveId, text: '', sender: 'bot' });
              }
              const m = session.messages.value.find(v => v.id === botMessageId);
              if (m) {
                const safe = sanitizeAssistantResponse(complete, evidence);
                m.text = composeBotMessageText(safe.main, safe.evidence);
              }
            }
          } catch (err) {
            // Do not echo a malformed server chunk into the browser console;
            // provider errors can contain internal tool payloads or SQL.
            console.error('Unable to parse an assistant stream event.', err);
          }
        }
        if (streamFailed) break;
      }
      debugChatLog('[useChat] stream ended');
      return { aborted: false };
    } catch (e: any) {
      if (e?.name === 'AbortError') {
        if (botMessageId === null && userMessageId !== null) {
          session.messages.value = session.messages.value.filter(v => v.id !== userMessageId);
        }
        if (botMessageId !== null && !complete.trim()) {
          session.messages.value = session.messages.value.filter(v => v.id !== botMessageId);
        }
        return { aborted: true };
      }
      console.error('Error communicating with API:', e?.message || e);
      session.messages.value.push({ id: Date.now(), text: 'Sorry, I could not process your request.', sender: 'bot' });
      return { aborted: false };
    } finally {
      session.isStreaming.value = false;
      session.streamAbortController = null;
    }
  };

  const toBase64 = (file: File) =>
    new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => (typeof reader.result === 'string' ? resolve(reader.result) : reject(new Error('FileReader result is not a string')));
      reader.onerror = reject;
    });

  const triggerImageUpload = () => { document.getElementById('image-input')?.click(); };
  const previewImage = (event: Event) => {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0] || null;
    if (!file) return;
    session.newImage.value = file;
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => { if (typeof reader.result === 'string') session.imagePreview.value = reader.result; };
  };

  const resetChat = async (newApiKey: string) => {
    stopMessage();
    session.apiKey = newApiKey;
    session.applicationId = '';
    session.chatId = '';
    session.initialized = false;
    session.initializing = null;
    session.isStreaming.value = false;
    session.streamAbortController = null;
    session.progressStatus.value = '';
    session.progressDetail.value = '';
    session.progressToolTrace.value = [];
    session.progressJudgeTrace.value = [];
    session.progressDraftPreview.value = null;
    session.messages.value = [];
    debugChatLog('[useChat] resetChat');
    await initializeChatSession(session);
    session.messages.value.push({ id: 1, text: CHAT_GREETING, sender: 'bot' });
  };

  void initializeChatSession(session);

  return {
    isChatOpen: session.isChatOpen,
    messages: session.messages,
    newMessage: session.newMessage,
    newImage: session.newImage,
    imagePreview: session.imagePreview,
    isStreaming: session.isStreaming,
    progressStatus: session.progressStatus,
    progressDetail: session.progressDetail,
    progressToolTrace: session.progressToolTrace,
    progressJudgeTrace: session.progressJudgeTrace,
    progressDraftPreview: session.progressDraftPreview,
    toggleChat,
    sendMessage,
    stopMessage,
    triggerImageUpload,
    previewImage,
    resetChat
  };
}
